services:
  api:
    build:
      context: .
      target: deps
    read_only: false
    command: npx ts-node-dev --respawn --transpile-only --poll src/server.ts
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./tsconfig.json:/app/tsconfig.json
      - ./client/storage/public/uploads:/app/client/storage/public/uploads
      - ./client/storage:/app/client/storage
    environment:
      NODE_ENV: development

  worker:
    build:
      context: .
      target: deps
    read_only: false
    command: npx ts-node-dev --respawn --transpile-only --poll src/jobs/run-workers.ts
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./tsconfig.json:/app/tsconfig.json
    environment:
      NODE_ENV: development

  migrate:
    command: npx prisma migrate dev
